
services:
  flaskapp:
    build: ./services/app
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/app/:/app
    ports:
      - 5001:5000
    env_file:
      - ./devel.env
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - ./services/db/data:/var/lib/postgresql/data
    env_file:
      - ./devel.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}


# Final
# services:
#   web:
#     build: ./services/web
#     command: python manage.py run -h 0.0.0.0
#     volumes:
#       - ./services/web/:/usr/src/app/
#     ports:
#       - 5001:5000
#     env_file:
#       - ./.env.dev
#     depends_on:
#       - db
#   db:
#     image: postgres:13
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     environment:
#       - POSTGRES_USER=${DB_U}
#       - POSTGRES_PASSWORD=hello_flask
#       - POSTGRES_DB=hello_flask_dev

# volumes:
#   postgres_data:
